### ISSUE TITLE
drysegs - heatmap edits?

### ISSUE THREAD

**Issue by rhull21** [rhull21/re_app#28]
@agropunk and @qi-ball, what 'significant' features should be rendered on the drysegs heatmap. Right now, it's all of the `features` in the database. Here are a few alternatives
* Select a few significant ones (e.g. reaches, Peralta Wasteway, etc). If so, which ones?
* Only the USGS gages
* Keep all features, but make it easier to turn them off
* Some other solution

(see also #29)

**Comment by agropunk** [comment]
@rhull21 do you know if there's a way to have it so that users can toggle on groups of features (gages, reach breaks, landmarks, etc), instead of having the list of all features that are individually toggled? People are usually familiar with the concept of toggling map layers on and off now, so something that fits that framework might be more intuitive. 

If that's not possible, starting with reach breaks seems good to me. I can also play around with the rendering of the feature layer. If there's a way to use different line weights, colors, line types for different feature types, that could make it more legible too.

**Comment by rhull21** [comment]
@agropunk this PR looks great! I really like the color contrasts it's so much better. 

I added a few changes in recent PR small plotly updates #69 

I agree, grouping the features could help. It's something I'll work on

**Comment by rhull21** [comment]
updated 0320203, commit 6eaf416
